### ISSUE TITLE
Prompt Should have Value=""

### ISSUE THREAD

**Issue by srsgores** [begedin/ember-select-list#16]
It turns out that when `prompt` is specified, in order for the `select` to **actually** be considered _invalid_, the `option` [**must** have its `value` set to `""`](http://stackoverflow.com/questions/15984430/how-to-set-a-default-prompt-when-nothing-selected-for-select-using-css).

See [this pen](http://codepen.io/srsgores/pen/PPpjxK) for example; when there is `value=""` on the prompt, the form submits; but when `value=""` is removed, the form does validation as expected.

I can make a PR, but the change is really quite trivial.

**Edit**: `disabled` does not affect the form validity.

**Comment by begedin** [comment]
@srsgores: The PR does what it should, but the tests are failing. I completely agree with your observations, so as soon as you fix the two issues in the PR (I would, but I don't have write access to your fork), I can merge.

**Comment by srsgores** [comment]
I just gave you write permissions to my fork.  If `validity` is false, then this means the feature isn't correctly implemented; `validity` is part of the HTML5 spec, so if the tests don't pass, the feature shouldn't be merged.

**Comment by srsgores** [comment]
I check on the inspector in Chrome, and `validity` behaves as expected in the pen I wrote.  So the tests should be written properly...

**Comment by begedin** [comment]
Fixed with #17
